import type {
  Video,
  Comment,
  AppNotification,
  User,
  WatchHistoryItem,
  Bookmark,
  Achievement,
  CategoryInfo,
  Playlist,
  Subscription,
  VideoCategory,
} from '@/types';

const now = Date.now();
const day = 86_400_000;

export const mockUser: User = {
  id: 'u_001',
  email: 'maya.rivers@storyverse.app',
  username: 'mayarivers',
  displayName: 'Maya Rivers',
  avatarUrl:
    'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop',
  coverUrl:
    'https://images.pexels.com/photos/110854/pexels-photo-110854.jpeg?auto=compress&cs=tinysrgb&w=900&h=400&fit=crop',
  bio: 'Filmmaker & content creator. Sharing cinematic stories and behind-the-scenes moments.',
  location: 'Los Angeles, CA',
  role: 'creator',
  isVerified: true,
  isCreator: true,
  isPremium: true,
  premiumExpiresAt: now + day * 180,
  suspendStatus: "active" as const,
  socialLinks: {
    twitter: 'https://twitter.com/mayarivers',
    instagram: 'https://instagram.com/mayarivers',
    youtube: 'https://youtube.com/@mayarivers',
    website: 'https://mayarivers.com',
  },
  followersCount: 12480,
  followingCount: 312,
  subscribersCount: 8420,
  videosCount: 47,
  totalViews: 982_103,
  totalLikes: 184_220,
  watchTimeMinutes: 1840,
  preferredCategories: ['Technology', 'Gaming', 'Music'],
  joinedAt: now - day * 220,
  createdAt: now - day * 220,
  updatedAt: now - day * 2,
};

function fillVideo(v: Partial<Video> & Pick<Video, 'id' | 'title' | 'description' | 'category' | 'videoUrl' | 'thumbnailUrl' | 'durationSeconds' | 'viewsCount' | 'likesCount' | 'commentsCount' | 'creatorId' | 'creatorName' | 'createdAt' | 'updatedAt'>): Video {
  return {
    tags: [],
    visibility: 'public' as const,
    status: 'published' as const,
    bookmarksCount: Math.round((v.likesCount ?? 0) * 0.3),
    isFeatured: false,
    isTrending: false,
    isNew: false,
    trendingScore: Math.round((v.viewsCount ?? 0) / 1000),
    creatorAvatarUrl: null,
    creatorIsVerified: false,
    likedByMe: false,
    bookmarkedByMe: false,
    subscribedToCreator: false,
    releasedAt: v.createdAt,
    ...v,
  } as Video;
}

export const mockVideos: Video[] = ([
  {
    id: 'v_001',
    title: 'Building a Neural Network from Scratch',
    description: 'A deep dive into how neural networks work under the hood. We build one from scratch using only Python and numpy — no frameworks, no shortcuts.',
    category: 'Technology',
    videoUrl: 'https://res.cloudinary.com/dbj6koi4f/video/upload/v1717000000/sample-video.mp4',
    thumbnailUrl:
      'https://images.pexels.com/photos/2156881/pexels-photo-2156881.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
    durationSeconds: 1680,
    viewsCount: 982_103,
    likesCount: 184_220,
    commentsCount: 12_402,
    isFeatured: true,
    isTrending: true,
    isNew: false,
    trendingScore: 982,
    creatorId: 'c_001',
    creatorName: 'Aether Studios',
    creatorAvatarUrl:
      'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop',
    creatorIsVerified: true,
    tags: ['programming', 'AI', 'education'],
    releasedAt: now - day * 30,
    createdAt: now - day * 30,
    updatedAt: now - day * 5,
  },
  {
    id: 'v_002',
    title: 'The Art of Cinematic Color Grading',
    description: 'How professional colorists transform flat footage into cinematic gold. We cover LUTs, node trees, and the psychology of color.',
    category: 'Movies',
    videoUrl: 'https://res.cloudinary.com/dbj6koi4f/video/upload/v1717000001/sample-video.mp4',
    thumbnailUrl:
      'https://images.pexels.com/photos/2086361/pexels-photo-2086361.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
    durationSeconds: 1920,
    viewsCount: 442_300,
    likesCount: 88_120,
    commentsCount: 5_881,
    isFeatured: false,
    isTrending: true,
    isNew: true,
    trendingScore: 442,
    creatorId: 'c_002',
    creatorName: 'Hollow Compass',
    creatorAvatarUrl:
      'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop',
    creatorIsVerified: false,
    tags: ['filmmaking', 'color', 'tutorial'],
    releasedAt: now - day * 6,
    createdAt: now - day * 6,
    updatedAt: now - day * 1,
  },
  {
    id: 'v_003',
    title: 'Speedrunning Elden Ring — World Record Attempt',
    description: 'Watch as I attempt to break the world record for the fastest Elden Ring playthrough. Every boss, every shortcut, no deaths.',
    category: 'Gaming',
    videoUrl: 'https://res.cloudinary.com/dbj6koi4f/video/upload/v1717000002/sample-video.mp4',
    thumbnailUrl:
      'https://images.pexels.com/photos/129731/pexels-photo-129731.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
    durationSeconds: 5400,
    viewsCount: 603_440,
    likesCount: 102_330,
    commentsCount: 7_201,
    isFeatured: false,
    isTrending: false,
    isNew: true,
    trendingScore: 603,
    creatorId: 'c_003',
    creatorName: 'Verdant Lens',
    creatorAvatarUrl:
      'https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop',
    creatorIsVerified: true,
    tags: ['gaming', 'speedrun', 'elden-ring'],
    releasedAt: now - day * 3,
    createdAt: now - day * 3,
    updatedAt: now - day * 1,
  },
  {
    id: 'v_004',
    title: 'Lo-Fi Beats to Study/Relax to — Live Radio',
    description: '24/7 lo-fi hip hop beats for studying, relaxing, or coding. Grab a coffee and let the beats flow.',
    category: 'Music',
    videoUrl: 'https://res.cloudinary.com/dbj6koi4f/video/upload/v1717000003/sample-video.mp4',
    thumbnailUrl:
      'https://images.pexels.com/photos/110854/pexels-photo-110854.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
    durationSeconds: 3600,
    viewsCount: 1_204_900,
    likesCount: 241_900,
    commentsCount: 18_001,
    isFeatured: true,
    isTrending: false,
    isNew: false,
    trendingScore: 1205,
    creatorId: 'c_004',
    creatorName: 'Orbit Nine',
    creatorAvatarUrl:
      'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop',
    creatorIsVerified: true,
    tags: ['lofi', 'music', 'study'],
    releasedAt: now - day * 45,
    createdAt: now - day * 45,
    updatedAt: now - day * 8,
  },
  {
    id: 'v_005',
    title: 'I Cooked for Gordon Ramsay and He Said...',
    description: 'I spent 30 days perfecting a single dish and invited Gordon Ramsay to try it. The result was not what I expected.',
    category: 'Cooking',
    videoUrl: 'https://res.cloudinary.com/dbj6koi4f/video/upload/v1717000004/sample-video.mp4',
    thumbnailUrl:
      'https://images.pexels.com/photos/1438761/pexels-photo-1438761.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
    durationSeconds: 720,
    viewsCount: 318_990,
    likesCount: 61_002,
    commentsCount: 3_120,
    isFeatured: false,
    isTrending: true,
    isNew: false,
    trendingScore: 319,
    creatorId: 'c_005',
    creatorName: 'Salt & Silence',
    creatorAvatarUrl:
      'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop',
    creatorIsVerified: false,
    tags: ['cooking', 'gordon-ramsay', 'challenge'],
    releasedAt: now - day * 15,
    createdAt: now - day * 15,
    updatedAt: now - day * 4,
  },
  {
    id: 'v_006',
    title: 'Exploring Abandoned Tokyo — Under the City',
    description: 'We venture into the forgotten underground tunnels beneath Tokyo. What we found was incredible and terrifying.',
    category: 'Travel',
    videoUrl: 'https://res.cloudinary.com/dbj6koi4f/video/upload/v1717000005/sample-video.mp4',
    thumbnailUrl:
      'https://images.pexels.com/photos/2387873/pexels-photo-2387873.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
    durationSeconds: 1080,
    viewsCount: 211_220,
    likesCount: 42_001,
    commentsCount: 2_220,
    isFeatured: false,
    isTrending: false,
    isNew: true,
    trendingScore: 211,
    creatorId: 'c_006',
    creatorName: 'Night Thread',
    creatorAvatarUrl:
      'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop',
    creatorIsVerified: false,
    tags: ['travel', 'abandoned', 'tokyo'],
    releasedAt: now - day * 2,
    createdAt: now - day * 2,
    updatedAt: now - day * 1,
  },
  {
    id: 'v_007',
    title: 'The Funniest Comedy Clips of 2026',
    description: 'A compilation of the best stand-up comedy moments from this year. Warning: may cause uncontrollable laughter.',
    category: 'Comedy',
    videoUrl: 'https://res.cloudinary.com/dbj6koi4f/video/upload/v1717000006/sample-video.mp4',
    thumbnailUrl:
      'https://images.pexels.com/photos/235621/pexels-photo-235621.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
    durationSeconds: 600,
    viewsCount: 388_002,
    likesCount: 77_050,
    commentsCount: 4_010,
    isFeatured: true,
    isTrending: true,
    isNew: false,
    trendingScore: 388,
    creatorId: 'c_007',
    creatorName: 'Petalworks',
    creatorAvatarUrl:
      'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop',
    creatorIsVerified: true,
    tags: ['comedy', 'standup', 'compilation'],
    releasedAt: now - day * 55,
    createdAt: now - day * 55,
    updatedAt: now - day * 10,
  },
  {
    id: 'v_008',
    title: 'How This 17-Year-Old Built a $1M App',
    description: 'An interview with a teenage entrepreneur who built and launched a profitable app while still in high school.',
    category: 'Technology',
    videoUrl: 'https://res.cloudinary.com/dbj6koi4f/video/upload/v1717000007/sample-video.mp4',
    thumbnailUrl:
      'https://images.pexels.com/photos/356056/pexels-photo-356056.jpeg?auto=compress&cs=tinysrgb&w=600&h=400&fit=crop',
    durationSeconds: 1440,
    viewsCount: 142_001,
    likesCount: 28_900,
    commentsCount: 1_201,
    isFeatured: false,
    isTrending: false,
    isNew: true,
    trendingScore: 142,
    creatorId: 'c_008',
    creatorName: 'Polar Frequency',
    creatorAvatarUrl:
      'https://images.pexels.com/photos/1139743/pexels-photo-1139743.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop',
    creatorIsVerified: false,
    tags: ['startup', 'tech', 'interview'],
    releasedAt: now - day * 2,
    createdAt: now - day * 2,
    updatedAt: now - day * 1,
  },
] as any[]).map(fillVideo);

export const mockContinueWatching: WatchHistoryItem[] = [
  {
    id: 'w_001',
    userId: mockUser.id,
    videoId: 'v_001',
    progress: 0.68,
    progressSeconds: 1140,
    durationSeconds: 1680,
    completionPercentage: 68,
    completed: false,
    lastWatchedAt: now - day * 0.2,
  },
  {
    id: 'w_002',
    userId: mockUser.id,
    videoId: 'v_003',
    progress: 0.4,
    progressSeconds: 2160,
    durationSeconds: 5400,
    completionPercentage: 40,
    completed: false,
    lastWatchedAt: now - day * 1.2,
  },
  {
    id: 'w_003',
    userId: mockUser.id,
    videoId: 'v_008',
    progress: 0.86,
    progressSeconds: 1240,
    durationSeconds: 1440,
    completionPercentage: 86,
    completed: false,
    lastWatchedAt: now - day * 2.5,
  },
];

export const mockComments: Comment[] = [
  {
    id: 'cm_001',
    videoId: 'v_001',
    authorId: 'u_002',
    authorName: 'orion_v',
    authorAvatarUrl:
      'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop',
    authorIsCreator: false,
    body: 'This is the best explanation of neural networks I have ever seen. The visualizations are incredible.',
    likesCount: 248,
    repliesCount: 12,
    isLikedByMe: false,
    isPinned: true,
    isEdited: false,
    parentId: null,
    createdAt: now - day * 2,
    updatedAt: now - day * 2,
  },
  {
    id: 'cm_002',
    videoId: 'v_001',
    authorId: 'u_003',
    authorName: 'sage.builds',
    authorAvatarUrl:
      'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop',
    authorIsCreator: false,
    body: 'Followed along and built it myself. Thank you for making this accessible to everyone!',
    likesCount: 132,
    repliesCount: 4,
    isLikedByMe: true,
    isPinned: false,
    isEdited: false,
    parentId: null,
    createdAt: now - day * 1.5,
    updatedAt: now - day * 1.5,
  },
];

export const mockBookmarks: Bookmark[] = [
  {
    id: 'b_001',
    userId: mockUser.id,
    videoId: 'v_002',
    playlistId: null,
    createdAt: now - day * 4,
  },
  {
    id: 'b_002',
    userId: mockUser.id,
    videoId: 'v_004',
    playlistId: null,
    createdAt: now - day * 7,
  },
  {
    id: 'b_003',
    userId: mockUser.id,
    videoId: 'v_007',
    playlistId: null,
    createdAt: now - day * 12,
  },
];

export const mockNotifications: AppNotification[] = [
  {
    id: 'n_001',
    userId: mockUser.id,
    type: 'new_video',
    title: 'New video from Aether Studios',
    body: 'Building a Neural Network from Scratch is now available.',
    imageUrl:
      'https://images.pexels.com/photos/2156881/pexels-photo-2156881.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop',
    actorAvatarUrl: null,
    targetVideoId: 'v_001',
    read: false,
    createdAt: now - day * 0.1,
  },
  {
    id: 'n_002',
    userId: mockUser.id,
    type: 'like',
    title: 'orion_v liked your video',
    body: 'Your video "Building a Neural Network from Scratch" received a new like.',
    imageUrl: null,
    actorAvatarUrl:
      'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop',
    targetVideoId: 'v_001',
    read: false,
    createdAt: now - day * 0.4,
  },
  {
    id: 'n_003',
    userId: mockUser.id,
    type: 'new_subscriber',
    title: 'sage.builds subscribed to you',
    body: 'You have a new subscriber. Keep creating great content!',
    imageUrl: null,
    actorAvatarUrl:
      'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop',
    targetVideoId: null,
    read: true,
    createdAt: now - day * 1.2,
  },
  {
    id: 'n_004',
    userId: mockUser.id,
    type: 'comment',
    title: 'New comment on your video',
    body: 'sage.builds: "Followed along and built it myself. Thank you!"',
    imageUrl: null,
    actorAvatarUrl:
      'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop',
    targetVideoId: 'v_001',
    read: true,
    createdAt: now - day * 2,
  },
  {
    id: 'n_005',
    userId: mockUser.id,
    type: 'video_upload_complete',
    title: 'Your video is ready',
    body: 'Your video has been processed and is now live for your audience.',
    imageUrl: null,
    actorAvatarUrl: null,
    targetVideoId: null,
    read: true,
    createdAt: now - day * 6,
  },
  {
    id: 'n_006',
    userId: mockUser.id,
    type: 'new_follower',
    title: 'night_thread started following you',
    body: 'You have a new follower. Keep up the great work!',
    imageUrl: null,
    actorAvatarUrl:
      'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop',
    targetVideoId: null,
    read: false,
    createdAt: now - day * 0.3,
  },
  {
    id: 'n_007',
    userId: mockUser.id,
    type: 'reply',
    title: 'orion_v replied to your comment',
    body: 'Great point! I had the same experience.',
    imageUrl: null,
    actorAvatarUrl:
      'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=80&h=80&fit=crop',
    targetVideoId: 'v_001',
    read: true,
    createdAt: now - day * 3,
  },
];

export const mockAchievements: Achievement[] = [
  {
    id: 'a_001',
    name: 'First Video',
    description: 'Upload your first video',
    iconName: 'Video',
    unlockedAt: now - day * 200,
    progress: 1,
    target: 1,
  },
  {
    id: 'a_002',
    name: 'Night Owl',
    description: 'Watch 10 videos after midnight',
    iconName: 'Moon',
    unlockedAt: now - day * 60,
    progress: 10,
    target: 10,
  },
  {
    id: 'a_003',
    name: 'Category Explorer',
    description: 'Watch videos from 5 categories',
    iconName: 'Compass',
    unlockedAt: null,
    progress: 3,
    target: 5,
  },
  {
    id: 'a_004',
    name: 'Collector',
    description: 'Save 25 videos to your library',
    iconName: 'Bookmark',
    unlockedAt: null,
    progress: 12,
    target: 25,
  },
  {
    id: 'a_005',
    name: 'Marathoner',
    description: 'Watch 1000 minutes total',
    iconName: 'Flame',
    unlockedAt: now - day * 30,
    progress: 1840,
    target: 1000,
  },
];

export const mockCategoryCategories: CategoryInfo[] = [
  { id: 'g_1', name: 'Comedy', color: '#14B8A6', iconName: 'Laugh', videosCount: 128 },
  { id: 'g_2', name: 'Education', color: '#3B82F6', iconName: 'GraduationCap', videosCount: 96 },
  { id: 'g_3', name: 'Music', color: '#A855F7', iconName: 'Music', videosCount: 74 },
  { id: 'g_4', name: 'Sports', color: '#EF4444', iconName: 'Trophy', videosCount: 62 },
  { id: 'g_5', name: 'Movies', color: '#F59E0B', iconName: 'Film', videosCount: 88 },
  { id: 'g_6', name: 'Gaming', color: '#22C55E', iconName: 'Gamepad2', videosCount: 154 },
  { id: 'g_7', name: 'Technology', color: '#06B6D4', iconName: 'Cpu', videosCount: 91 },
  { id: 'g_8', name: 'Lifestyle', color: '#EC4899', iconName: 'Sparkles', videosCount: 39 },
];

export const mockPlaylists: Playlist[] = [
  {
    id: 'p_001',
    userId: mockUser.id,
    title: 'Watch Later',
    description: 'Videos I want to watch later',
    coverUrl: 'https://images.pexels.com/photos/2156881/pexels-photo-2156881.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
    videoIds: ['v_002', 'v_004', 'v_007'],
    isPrivate: false,
    type: 'watch_later',
    videoCount: 3,
    createdAt: now - day * 30,
    updatedAt: now - day * 2,
  },
  {
    id: 'p_002',
    userId: mockUser.id,
    title: 'Programming Tutorials',
    description: 'My favorite coding tutorials',
    coverUrl: 'https://images.pexels.com/photos/356056/pexels-photo-356056.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
    videoIds: ['v_001', 'v_008'],
    isPrivate: false,
    type: 'custom',
    videoCount: 2,
    createdAt: now - day * 60,
    updatedAt: now - day * 5,
  },
  {
    id: 'p_003',
    userId: mockUser.id,
    title: 'Favorites',
    description: 'My all-time favorite videos',
    coverUrl: 'https://images.pexels.com/photos/129731/pexels-photo-129731.jpeg?auto=compress&cs=tinysrgb&w=400&h=300&fit=crop',
    videoIds: ['v_003', 'v_005'],
    isPrivate: false,
    type: 'favorites',
    videoCount: 2,
    createdAt: now - day * 90,
    updatedAt: now - day * 10,
  },
];

export const mockSubscriptions: Subscription[] = [
  {
    id: 'sub_001',
    subscriberId: mockUser.id,
    creatorId: 'c_001',
    createdAt: now - day * 90,
  },
  {
    id: 'sub_002',
    subscriberId: mockUser.id,
    creatorId: 'c_004',
    createdAt: now - day * 45,
  },
];

export const mockTrendingSearches: string[] = [
  'neural network',
  'cinematic color grading',
  'elden ring speedrun',
  'lofi beats',
  'cooking challenge',
  'abandoned tokyo',
];

export const mockRecentSearches: string[] = [
  'technology',
  'gaming',
  'lofi music',
  'Aether Studios',
];

export const mockCategories: VideoCategory[] = [
  'Comedy',
  'Gaming',
  'Music',
  'Technology',
  'Education',
  'Sports',
  'Movies',
  'Lifestyle',
  'Entertainment',
  'News',
  'Travel',
  'Cooking',
];
